# Generated by Django 2.2.5 on 2020-07-14 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='latex',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='latex',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
